# Generated by Django 3.2.6 on 2021-08-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('environment', 'Environment'), ('technology', 'Technology'), ('education', 'Education'), ('health', 'Health'), ('science', 'Science'), ('travel', 'Travel')], default='world', max_length=50),
        ),
    ]
